# config/cloudinary.yml
#ENV["CLOUD_NAME"]
development:
  cloud_name: ENV["CLOUD_NAME"]
  api_key: ENV["CLOUD_KEY"]
  api_secret: ENV["CLOUD_SECRET"]

production:
  cloud_name: ENV["CLOUD_NAME"]
  api_key: ENV["CLOUD_KEY"]
  api_secret: ENV["CLOUD_SECRET"]
